insert into config (
    FermenterSensor     ,
    PresenceZero        ,
    PresenceCalibration ,
    PresenceOnTimer     ,
    PresenceEnabled     ,
    PresenceTimeout     ,
    TemperatureScale    ,
    TargetTemperature   ,
    PidSlope            ,
    NpaZero             ,
    NpaCalibration      ,
    Tec1Threshold       ,
    Tec1Min             ,
    Tec1Max             ,
    Tec2Threshold       ,
    Tec2Min             ,
    Tec2Max             ,
    Fan1Threshold       ,
    Fan1Min             ,
    Fan1Max             ,
    Fan2Threshold       ,
    Fan2Min             ,
    Fan2Max             ,
    Pump1Threshold      ,
    Pump1Min            ,
    Pump1Max            ,
    Pump2Threshold      ,
    Pump2Min            ,
    Pump2Max            ,
    NpaMinValue         ,
    NpaMaxValue         ,
    NpaMinPressure      ,
    NpaMaxPressure      ,
    Stage		        ,
    OG		            ,
    BrewingStartTime    ,
    PitchTime
) values (
    "",
    4100,
    1000,
    4,
    1,
    15,
    0,
    21.1,
    2.55,
    0,
    0,
    0,
    0,
    255,
    0,
    0,
    255,
    3,
    50,
    235,
    3,
    50,
    235,
    1,
    30,
    200,
    1,
    30,
    230,
    1638,
    14745,
    -6894.76,
    6894.76,
    0,
    0,
    0,
    0
)